### ISSUE TITLE
Handle users with permissions below the `standard` global role

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10787]
- The `standard` global role has permissions on resources that some users don't wish to assign
- They fall back on the `user-base` global role and then add more granular context specific roles such a `cluster-owner` or `project-owner`
- The combination of `user-base` and context roles don't have all the permissions required for the user to execute on the functionality of those context roles
  - Specifically they normally lack access to global resources that the UI uses to manage those contexts. For example
    - `user-base` + `cluster-owner` does not contain permissions to see role templates, stored globally, so user cannot select a role from a list to assign to a user
    - `user-base` + `project-owner` does not contain permissions to list users, stored globally, so users cannot select a user to asssign a role to
    - `user-base` + `cluster-owner`  does not contain permissions to list node templates, so users cannot manage nodes in the cluster
  - This can result in errors in page which then fail to cause it to render or function correctly

### Investigation Tasks
- [ ] With a user who has the global `user-base` role and a specific cluster's `cluster-owner` role investigate what fails and degrade gracefully - https://github.com/rancher/dashboard/issues/11598
- [ ] With a user who has the global `user-base` role and a specific project's `project-owner` role investigate what fails and degrade gracefully - https://github.com/rancher/dashboard/issues/11599
- [ ] Combine info (additional permissions needed for the area's to render all content / all functionality works) from two issues above. Provide to the docs team to make public

### Solution Tasks
Given above there could be a number of solutions, at the moment we would err towards the creation of a set of new global roles to cover a reasonable set of functionality (given we don't know precisely which features the admin is trying to expose to users). To be discussed with frameworks/collie.

**Comment by richard-cox** [comment]
Related Issues
- https://github.com/rancher/dashboard/issues/9804
- https://github.com/rancher/dashboard/issues/10560

**Comment by IsaSih** [comment]
When in QA, verify if the following no longer occurs: https://github.com/rancher/dashboard/issues/10156#issuecomment-2067354519

**Comment by gaktive** [comment]
As the milestones get moved around here, if this goes to 2.12, we'll need a 2.11.x backport though I'll have to make the .1 milestone first.

**Comment by nwmac** [comment]
@richard-cox Can I bump this epic to 2.13?
