### ISSUE TITLE
Resources left to port over 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1147]
- [ ] workloads (sidecars)
- [ ] Projects - rancher/dashboard#567
- [ ] Nodes (edit) - rancher/dashboard#557
- [ ] HPA - rancher/dashboard#253
- [ ] Storage Classes
- [ ] Persistent Volumes
- [ ] Authentication
   - [ ] Github
   - [ ] Azure AD
   - [ ] AD
   - [ ] Ping
   - [ ] Keycloak
   - [ ]  ADFS
   - [ ] Okta
   - [ ] Shibboleth
   - [ ] FreeIPA
   - [ ] OpenLDAP
   - [ ] Google

**Comment by deniseschannon** [comment]
Closing in favor of tracking in other places/issues
