### ISSUE TITLE
[Epic] Vue 3 Migration of our own extensions

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#11477]
**Is your feature request related to a problem? Please describe.**

Vue 3 Migration of our own extensions, such as:

- [x] Elemental: https://github.com/rancher/elemental-ui https://github.com/rancher/dashboard/issues/12182 (needs full testing with a proper Shell release that fixes all remaining problems, but 95% done)
- [x] Kubewarden: https://github.com/rancher/kubewarden-ui https://github.com/rancher/dashboard/issues/12183 (needs full testing with a proper Shell release that fixes all remaining problems, but 95% done)
- [x] CAPI 🐢 : https://github.com/rancher/capi-ui-extension https://github.com/rancher/dashboard/issues/12184
- [x] Neuvector: https://github.com/neuvector/manager-ext https://github.com/neuvector/manager-ext/pull/80
- [x] Stackstate : https://github.com/StackVista/rancher-extension-stackstate https://github.com/rancher/dashboard/issues/12185 - https://github.com/StackVista/rancher-extension-stackstate/pull/24

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cnotv** [comment]
@aalves08 are we tracking this issue or can we close?

**Comment by aalves08** [comment]
@cnotv is there any other issue to track this?

**Comment by cnotv** [comment]
I doubt so, but that sounds like we use this to track then 😅

**Comment by aalves08** [comment]
Closing epic since all official extensions have been migrated to Vue3 (code changes merged)

FYI @gaktive @nwmac @richard-cox @jordojordo
