### ISSUE TITLE
Move to new public api token endpoint

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12488]
- [ ] https://github.com/rancher/dashboard/issues/12331
- [ ] Use generateKubeconfig which returns new token (TBD)
- [ ] https://github.com/rancher/dashboard/issues/12332

**Comment by richard-cox** [comment]
Blocked given https://github.com/rancher/dashboard/issues/12331

We should also consider this blocked on release on https://github.com/rancher/rancher/issues/51220

**Comment by nwmac** [comment]
Pushing the epic in 2.15.0 - we will/may do some of this in 2.14.0

**Comment by nwmac** [comment]
@richard-cox Should we push this to 2.16.0?
