### ISSUE TITLE
Workload Polish

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1769]
Here are a list of issue already entered for Workload to polish it up:

General (across more then 1 tab):
- [x] Move Schedule section out of Container & into the top section.  It has nothing to do with Container - rancher/dashboard#1717

- [x] Update headers/tabs (Naming, order) - https://docs.google.com/document/d/1WR1ZWruGQEFMNtSjj25zzrFhGJBIeCBvGnZFSXiOkxY/edit?usp=sharing

- [x] Namespace Drop-down in Create: Clear button for drop-down need fixing - rancher/dashboard#1736 

- [x] All Sections in a tab should have a Header (remove lines) - rancher/dashboard#1718 

- [x] Change drop-down button with two options to two buttons: Environment Variable & Node Scheduling labels - rancher/dashboard#1723 

- [x] Change drop-downs that have less then 10 finite choices to non-searchable - rancher/dashboard#1722 

- [x] Buttons on same page and in general are using 2 or 3 different styles?  They should all look same, (Port, Add label... etc...) rancher/dashboard#1721 

- [x] Scroll for integers is showing up on dividing line - (example - Resources CPU Res) - rancher/dashboard#1729 

- [x] Drop-down border & cursor misaligned - rancher/dashboard#1725

- [ ] Tooltip Issues - Spacing, remove ProTip:, Startup Check doesn't have a recommended or not recommended.  Since the other two do, we should add one or remove the other two?

- [ ] General Spacing issue - Spacing Tabs & Top section, headers & fields, between fields & at end of section to next header is not consistent.  Spacing need to be fixed.

Container:
- [x] Fix Port section - rancher/dashboard#1727 

Pod & Node Selector tab:
- [x] Update block component on Pod & Node selector tabs (so they are consistent across the apps & resources) rancher/dashboard#1737 

- [x] Change Add Namespace to multi-select component in Pod scheduling - rancher/dashboard#1742 

- [x] Node & Pod Selector tab redesign - rancher/dashboard#1726 

Security Context tab

- [x] Fix Add/Drop component in Security for Add/Drop Capabilities - rancher/dashboard#1741 

Storage
- [x] Storage section needs styling & different kind of drop-down - # 1731

- [x] Storage blocks & Volume Claim templates block fields need styling.  Also strange I have a Volume drop-down in Storage then a Volume tab? - No issue

Statefulset Resource only
- [x] StatefulSet Create, the Service name should filter according to the Namespace drop-down that the resource is being created in - rancher/dashboard#1735 

- [x] StatefulSet Create - Volume Claim template needs new block style & fields need redesign. (no separate issue)

**Comment by tfiduccia** [comment]
Fixed & all associated bug are closed.
