### ISSUE TITLE
EPIC: net new without backend

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2851]
These are tickets for 2.6 with no backend requirements, meaning that they're 99.9% UI

- [x] Login UX & User Preferences: https://github.com/rancher/dashboard/issues/2136
- [x] Single Cluster Install Experience: https://github.com/rancher/dashboard/issues/2795
- [x] White labelling: https://github.com/rancher/dashboard/issues/2794
- [x] Green labelling: https://github.com/rancher/dashboard/issues/2506 & https://github.com/rancher/dashboard/issues/2497
- [x] Unified UI: https://github.com/rancher/dashboard/issues/2849

**Comment by sowmyav27** [comment]
Closing as issues are tracked separately
