### ISSUE TITLE
EPIC: see Ember pages in Dashboard, be they ported or embedded

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2951]
Translating the work being being done/to be done to ensure that going forward, most active functionality in the UI is done through Vue (aka here, the Dashboard)

Port:
- [x] https://github.com/rancher/dashboard/issues/2673 Port Project Membership functionality from Ember UI
- [x] https://github.com/rancher/dashboard/issues/2500 Port Project management functionality from Ember UI
- [x] https://github.com/rancher/dashboard/issues/2501 Port Cluster Membership functionality from Ember UI
- [x] https://github.com/rancher/dashboard/issues/2362 Port from Ember: ability to add namespace inline when deploying from helm chart 

Embed:
- [x] https://github.com/rancher/dashboard/issues/2514 Prototype embedding specific Ember pages within the Dashboard UI
- [x] https://github.com/rancher/dashboard/issues/2160 Embed from Ember: Snapshots - RKE2 Linux or RKE1 Windows
- [x] https://github.com/rancher/dashboard/issues/2757 iFrame from Ember: Custom UI Cluster Drivers
- [x] https://github.com/rancher/dashboard/issues/2917 Cluster Management for RKE (Embedded Ember UI)
- [x] https://github.com/rancher/dashboard/issues/2738 iFrame from Ember: AKS v2

Legacy:
- [x] https://github.com/rancher/dashboard/issues/3287 Istio v1, CIS Scans v1, Pipelines & Pipeline epic

**Comment by gaktive** [comment]
Maybe https://github.com/rancher/dashboard/issues/3287 can be folded directly into this.

**Comment by gaktive** [comment]
@nwmac there may be tickets that I'm missing that cover the other ported pages. Let me know what they are and I can ensure QA's aware when they test.

**Comment by sowmyav27** [comment]
Closing this epic as there are separate issues tracking all pages.
