### ISSUE TITLE
EPIC: With legacy feature off, will Dashboard UI work without Ember?

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3287]
There was a change in master-head last night that turned off the legacy feature flag by default unless in an upgrade. On upgrade, it should automatically be turned on.

https://github.com/rancher/rancher/issues/33264 was created for QA to test specifically for the feature flag functionality where by it's Off on fresh install, On for upgrades with tests for turning it on/off.

Anything that is considered legacy will be turned off in the UI and behind the feature flag, which is accessing ember pages that have been deprecated in v2.5. Currently, by turning on the feature flag, you will have access to the full Cluster Manager UI, but that will soon be changing to only give you access only to the pages that are needed to manage tools that are being deprecated/phased out.

Expected UI behaviour: some Ember pages that were going to be left need to be brought over to Vue.
- [x] Pipeline: https://github.com/rancher/dashboard/issues/3300
- [x] Pipelines: https://github.com/rancher/dashboard/issues/3299
- [x] CIS Scans v1: https://github.com/rancher/dashboard/issues/3298
- [x] Istio v1: https://github.com/rancher/dashboard/issues/3297

**Comment by kravciak** [comment]
All issues in description are closed, closing EPIC
