### ISSUE TITLE
Project Monitoring in Rancher - Epic

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5982]
I created this issue to list all of the project monitoring work in one place so that we can track and triage it a little more easily.

# Research

- [x] To allow helm charts to manage what happens to helm chart values during upgrades, we need to document what the UI is doing. This research will allow the UI to place whatever values it wants added into a ConfigMap. Then the Helm chart itself can control what happens from there, based on the ConfigMap. More details in this issue: https://github.com/rancher/dashboard/issues/5904

# Bug Fixes

- [x] https://github.com/rancher/dashboard/issues/5879
- [x] https://github.com/rancher/dashboard/issues/5875
- [x] https://github.com/rancher/dashboard/issues/5820
- [ ] https://github.com/rancher/dashboard/issues/4737
- [ ] https://github.com/rancher/dashboard/issues/6042
- [x] https://github.com/rancher/dashboard/issues/5924 In the alerting-drivers helm chart, we need to disable the install button if no alerting driver is selected. 

# Enhancements

- [x] https://github.com/rancher/dashboard/issues/5885
- [x] https://github.com/rancher/dashboard/issues/5747
- [x] https://github.com/rancher/dashboard/issues/5746
- [ ] https://github.com/rancher/rancher-docs/issues/53 Note: Transferred to docs

# Issues for later milestones

- https://github.com/rancher/dashboard/issues/5961
- https://github.com/rancher/dashboard/issues/5713 This feature will make it convenient for project owners to use the alerting drivers helm chart. 
- https://github.com/rancher/dashboard/issues/5754

**Comment by catherineluse** [comment]
Closing this issue because the few remaining issues are now mostly scheduled for different releases, so they don't need to be packaged together anymore.
