### ISSUE TITLE
Ease-of-use enhancements - Epic

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5983]
I created this issue to help get attention on enhancements that are primarily UI-focused. These tickets may otherwise be overlooked because most of them don't correspond to new backend features. But taken together, they could help reduce a lot of friction for Rancher users, especially beginners. These are mainly about enhancing the UX for existing features, so it could fall to the UI team to drive them forward.

## Navigation and search

- [ ] https://github.com/rancher/dashboard/issues/5091 (possible dupe here https://github.com/rancher/dashboard/issues/4151)
- [x] https://github.com/rancher/dashboard/issues/5913
- [x] https://github.com/rancher/dashboard/issues/5816
- [x] https://github.com/rancher/dashboard/issues/5033
- [ ] https://github.com/rancher/dashboard/issues/4469
- [x] https://github.com/rancher/dashboard/issues/4306
- [x] https://github.com/rancher/dashboard/issues/5798
- [x] https://github.com/rancher/dashboard/issues/5287
- [x] https://github.com/rancher/dashboard/issues/4431

## Better UX for deploying apps on Kubernetes

The Ember UI required the user to know only a container image name to deploy and expose a workload, whereas the dashboard requires the user to know more about Kubernetes networking in order to expose the same workload in the same way. The UI could provide more information to users to point users in the right direction to reduce frustration and the number of times the user has to leave the UI to read docs.

- [x] https://github.com/rancher/dashboard/issues/4518
- [x] https://github.com/rancher/dashboard/issues/4974
- [x] https://github.com/rancher/dashboard/issues/5441
- [x] https://github.com/rancher/dashboard/issues/5654
- [ ] https://github.com/rancher/dashboard/issues/3089

## Tooltips

- [x] https://github.com/rancher/dashboard/issues/5902
- [x] https://github.com/rancher/dashboard/issues/5807
- [x] https://github.com/rancher/dashboard/issues/5885

## Validation

- [x] https://github.com/rancher/dashboard/issues/5975
- [ ] https://github.com/rancher/dashboard/issues/5666 - Giuseppe and I opened this one thinking it could help many users who are trying out Rancher for the first time by preventing them from setting the Rancher Server URL to localhost.
- [ ] https://github.com/rancher/dashboard/issues/5690 and https://github.com/rancher/dashboard/issues/5714 (possibly the same issue)
- [x] https://github.com/rancher/dashboard/issues/5354
- [ ] https://github.com/rancher/dashboard/issues/5211 (possible dupe of https://github.com/rancher/dashboard/issues/4444)
- [x] https://github.com/rancher/dashboard/issues/5184
- [x] https://github.com/rancher/dashboard/issues/5095
- [ ] https://github.com/rancher/dashboard/issues/5052 (async validation)
- [ ] https://github.com/rancher/dashboard/issues/4698
- [x] https://github.com/rancher/dashboard/issues/4575
- [x] https://github.com/rancher/dashboard/issues/4352
- [ ] https://github.com/rancher/dashboard/issues/4235 (possible dupe of https://github.com/rancher/dashboard/issues/4861)
- [x] https://github.com/rancher/dashboard/issues/2994
- [x] https://github.com/rancher/dashboard/issues/5903
- [x] https://github.com/rancher/dashboard/issues/5927
- [x] https://github.com/rancher/dashboard/issues/5676
- [x] https://github.com/rancher/dashboard/issues/5188
- [x] https://github.com/rancher/dashboard/issues/4465
- [x] https://github.com/rancher/dashboard/issues/3687

**Comment by kwwii** [comment]
Closing this as it seems to be a stale issue.
