### ISSUE TITLE
Epic: Improve Namespace Filtering

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6417]
Opening per discussion - Some UX design issues are related to each other, so we should track them as part of a project for the sake of a consistent design.

Filtering:
- [ ] https://github.com/rancher/dashboard/issues/6318
- [ ] https://github.com/rancher/dashboard/issues/6321
- [x] https://github.com/rancher/dashboard/issues/6322
- [x] https://github.com/rancher/dashboard/issues/6414
- [ ] https://github.com/rancher/dashboard/issues/4469
- [x] https://github.com/rancher/dashboard/issues/6414
- [ ] https://github.com/rancher/dashboard/issues/6415

**Comment by kwwii** [comment]
Redefining this to limit the scope

**Comment by kwwii** [comment]
Closing this epic
