### ISSUE TITLE
UX Design Epic: Apps & Marketplace

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6418]
Opening per discussion - Some UX design issues are related to each other, so we should track them as part of a project for the sake of a consistent design.

- [ ] https://github.com/rancher/dashboard/issues/6402
- [ ] https://github.com/rancher/dashboard/issues/5686
- [ ] https://github.com/rancher/dashboard/issues/5460
- [ ] https://github.com/rancher/dashboard/issues/5043
- [ ] https://github.com/rancher/dashboard/issues/3152 (also a navigation issue)
- [ ] https://github.com/rancher/dashboard/issues/3057
- [ ] https://github.com/rancher/dashboard/issues/2672
- [ ] https://github.com/rancher/dashboard/issues/2671

**Comment by catherineluse** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/6402
