### ISSUE TITLE
Epic: Make it easier to expose workloads

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6419]
Opening per discussion - Some UX design issues are related to each other, so we should track them as part of a project for the sake of a consistent design.

The UI could provide more information to users to point users in the right direction to reduce frustration and the number of times the user has to leave the UI to read docs.

- [ ] https://github.com/rancher/dashboard/issues/4518
- [x] https://github.com/rancher/dashboard/issues/4974
- [x] https://github.com/rancher/dashboard/issues/5441
- [ ] https://github.com/rancher/dashboard/issues/5654
- [x] https://github.com/rancher/dashboard/issues/2386
- [ ] https://github.com/rancher/dashboard/issues/6183

**Comment by nwmac** [comment]
Closing as won't fix.
