### ISSUE TITLE
Porting Resources into Dashboard

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#755]
2.5 Issue to track status of resources to port over. Updated based on what is done for 2.5. 

Each resource is expected to have a list page, create/edit page and detail page. 

- [x] Workloads - 
- [x] Load Balancing -> Ingresses rancher/dashboard#272
- [x] Service Discovery -> Services rancher/dashboard#573
- [x] Secrets (Secrets, Cert, Registry Credentials) -https://github.com/rancher/dashboard/issues/264
- [x] Config Maps - https://github.com/rancher/dashboard/issues/265
- [x] Namespaces - #567
- [x] Cluster Overview - rancher/dashboard#350
- [x] Nodes (No create page) rancher/dashboard#241

**Comment by deniseschannon** [comment]
These are all tracked in separate tickets at this point and moved remaining resources into a different issue: https://github.com/rancher/dashboard/issues/1147
