### ISSUE TITLE
a11y: [Epic]: Keyboard Navigation and associated focus display/role/aria-label

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7967]
- [ ] https://github.com/rancher/dashboard/issues/12769 -> https://github.com/rancher/dashboard/pull/12876
- [ ] https://github.com/rancher/dashboard/issues/12771 -> https://github.com/rancher/dashboard/pull/13019
- [ ] https://github.com/rancher/dashboard/issues/12772 -> https://github.com/rancher/dashboard/pull/13011
- [ ] https://github.com/rancher/dashboard/issues/12774 -> https://github.com/rancher/dashboard/pull/12958
- [ ] https://github.com/rancher/dashboard/issues/12775 -> https://github.com/rancher/dashboard/pull/12956
- [ ] https://github.com/rancher/dashboard/issues/12776 -> https://github.com/rancher/dashboard/pull/12966
- [ ] https://github.com/rancher/dashboard/issues/12777 -> https://github.com/rancher/dashboard/pull/13019
- [ ] https://github.com/rancher/dashboard/issues/12778 -> https://github.com/rancher/dashboard/pull/13011
- [ ] https://github.com/rancher/dashboard/issues/12779 -> https://github.com/rancher/dashboard/pull/13011
- [ ] https://github.com/rancher/dashboard/issues/12780 -> https://github.com/rancher/dashboard/pull/13177
- [ ] https://github.com/rancher/dashboard/issues/12781 -> https://github.com/rancher/dashboard/pull/13021
- [x] https://github.com/rancher/dashboard/issues/12782
- [ ] https://github.com/rancher/dashboard/issues/12783 -> https://github.com/rancher/dashboard/pull/13139
- [ ] https://github.com/rancher/dashboard/issues/12784 -> https://github.com/rancher/dashboard/pull/12966
- [ ] https://github.com/rancher/dashboard/issues/12785
- [ ] https://github.com/rancher/dashboard/issues/12786 -> https://github.com/rancher/dashboard/pull/12959
- [ ] https://github.com/rancher/dashboard/issues/12787 -> https://github.com/rancher/dashboard/pull/13123
- [ ] https://github.com/rancher/dashboard/issues/12790 -> https://github.com/rancher/dashboard/pull/13011
- [x] https://github.com/rancher/dashboard/issues/12791
- [x] https://github.com/rancher/dashboard/issues/12794
- [x] https://github.com/rancher/dashboard/issues/12795
- [x] https://github.com/rancher/dashboard/issues/12811

**Comment by kwwii** [comment]
https://github.com/rancher/dashboard/issues/7892

**Comment by kwwii** [comment]
https://github.com/rancher/dashboard/issues/7892

**Comment by rak-phillip** [comment]
I'm moving this epic to Review so that we can ensure that we move it to done after QA has passed.

**Comment by rak-phillip** [comment]
We can close this epic after #12791 passes QA. #12779 will be addressed as a priority in 2.12; no additional epic needed for this.

**Comment by rancher-max** [comment]
#12791 has officially passed QA and been closed so closing this as well.
