### ISSUE TITLE
Upgrade Ember to latest 3.x

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8072]
@nwmac to confirm what version to upgrade to but we're currently at 3.24 and the latest is deep into 4.x. This may be painful so 3.28 should be an attainable initial step. 4.x deprecates a few things per https://emberjs.com/releases/

- [x] https://github.com/rancher/dashboard/issues/11518
- [ ] Remove unused code (optional, can be split out to another epic/issue) & block access to Ember URL (dependent on pagination in Vue but all other Ember pages would be embedded)
- [ ] Update ember.js in rancher/ui to 3.28.x
- [ ] Update other dependencies (can be split out to another epic/issue)
- [ ] Update to 4.x (split out to another issue

**Comment by gaktive** [comment]
Ember will eventually go away so aside from some minor updates, we'll bump this unless we really have to do this.

**Comment by gaktive** [comment]
Putting this back into 2.10. Maybe we have to look at streamlining Ember if that helps remove component requirements.

**Comment by richard-cox** [comment]
@nwmac Do we want to prioritise the next step `Update ember.js in rancher/ui to 3.28.x` for 2.10.0, or should this be moved to 2.11.0?

**Comment by nwmac** [comment]
2.11

**Comment by codyrancher** [comment]
Do we want to do this at all anymore given the 2.12 deprecation?

**Comment by nwmac** [comment]
@codyrancher I think we can close.
