### ISSUE TITLE
Epic: Move AKS, EKS & GKE from Ember to Vue

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8083]
Currently, to provision public cloud clusters (AKS, EKS & GKE), the cloud provisioning pages are iFramed from Ember into Vue. 

- [x] https://github.com/rancher/dashboard/issues/8718
- [ ] AKS: rancher/dashboard#8965
- [x] EKS: rancher/dashboard#8966
- [x] GKE: rancher/dashboard#8967
- [x] Cluster & Node Drivers: https://github.com/rancher/dashboard/issues/9274

Since there's a lot of active work done on those platforms but we'd like to move away from Ember, we should port these over to Vue.

This ties into work done overall to evaluate other pages to move off Ember and onto Vue: https://github.com/rancher/dashboard/issues/8718

**Comment by richard-cox** [comment]
Just a note - cluster drivers affect the aks / eks / gke world, and node drivers RKE1 and RKE2

**Comment by gaktive** [comment]
Started with AKS for Q4.

**Comment by nwmac** [comment]
Discussed with @yonasberhe23 - this was the epic - the individual issues are being tested by QA
