### ISSUE TITLE
Update missing parts of extension docs

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#8310]
There are still some areas that need tackling in terms of documentation to cover all areas:
- [x] translations https://github.com/rancher/dashboard/pull/8417 @jordojordo 
- [x] routing (after POC https://github.com/rancher/dashboard/issues/8311) @aalves08 
- [x] publishing extensions (POC https://github.com/rancher/dashboard/issues/8312) @jordojordo 
- [x] product registration (after POC https://github.com/rancher/dashboard/issues/8311) @aalves08
