### ISSUE TITLE
[EPIC] Performance: SQLite backed cache & Server-Side Pagination

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8527]
- This issues covers the integration of server-side pagination with the dashboard
- This will come in a number of iterations, each will be listed here when agreed on

## Pre 2.9.0
- [x] rancher/dashboard#9478
- [x] rancher/dashboard#9499
- [x] rancher/dashboard#9545
- [x] rancher/dashboard#9964
- [x] https://github.com/rancher/dashboard/issues/11507
- [x] https://github.com/rancher/dashboard/issues/11495
- [x] https://github.com/rancher/dashboard/issues/11496

## 2.9.0 
- See https://github.com/rancher/dashboard/issues?q=is%3Aissue%20label%3Aarea%2Fserver-side-pagination%20milestone%3Av2.9.0%20

## 2.10.0
- See https://github.com/rancher/dashboard/issues?q=is%3Aissue%20label%3Aarea%2Fserver-side-pagination%20milestone%3Av2.10.0%20

## 2.11.0
- See https://github.com/rancher/dashboard/issues?q=is%3Aissue%20label%3Aarea%2Fserver-side-pagination%20milestone%3Av2.11.0%20 and ui project board

## 2.11.2
- See https://github.com/rancher/dashboard/issues?q=is%3Aissue%20label%3Aarea%2Fserver-side-pagination%20milestone%3Av2.11.1%20 and ui project board

## 2.12
- See https://github.com/rancher/dashboard/issues?q=is%3Aissue%20label%3Aarea%2Fserver-side-pagination%20milestone%3Av2.12.0%20 and ui project board
- Current Plan
  - Feature on by default, production ready.
    - Includes automatic updates to cached resources (covers resources in lists)
  - Integrated with 
    - Cluster Explorer mostly converted
      - minus cluster management (pending front and backend changes) style resources.
      - minus RBAC (pending steve support of norman endpoints) style resources.
      - includes application of selectors via api

## 2.13 (wip)
- Current Plan
  - Integrated with 
    - Side Nav Clusters
  - Improved support for HA
- Flux
  - More complex sorting
  - [ ] Compare / Record filtering requirements from shell/components/SortableTable/filtering.js, discuss with backend
  - [ ] https://github.com/rancher/dashboard/issues/13044

## 2.14 (wip)
- Current Plan
 - workload page
 - Integrated with 
    - Home Page Clusters
    - Cluster Management, RBAC and all other related resources
  - Rancher Extensions integration 
    - Can be done out of rancher release cycle

## 2.15(wip)
- Current Plan
 - workload page
 - Integrated with 
    - RBAC related resources (roles, bindings). global, cluster,  project/namespace
    - Projects/Namespaces(?)
    - Catalog(?)
  - Rancher Extensions integration 
    - Can be done out of rancher release cycle

- Flux
  - More complex sorting
  - [ ] Compare / Record filtering requirements from shell/components/SortableTable/filtering.js, discuss with backend
  - [ ] https://github.com/rancher/dashboard/issues/13044

# Backend Issues (not complete list)
- https://github.com/rancher/rancher/issues/45635
- https://github.com/rancher/rancher/issues/46348
- https://github.com/rancher/rancher/issues/48042
- https://github.com/rancher/rancher/issues/47825
- Specifically
  - sort/filter on all labels plus label selectors support - https://github.com/rancher/rancher/issues/46333
  - updates to lists given websockets - https://github.com/rancher/rancher/issues/40773
  - ad-hoc requests (as required) to sort/filter on resource properties 
    - https://github.com/rancher/rancher/issues/46642
    - https://github.com/rancher/rancher/issues/48011
    - https://github.com/rancher/rancher/issues/48103
  - feature blocking, but not ui - https://github.com/rancher/rancher/issues/46768
  - https://github.com/rancher/rancher/issues/48092

Related
- https://github.com/rancher/dashboard/issues/11993
- https://github.com/rancher/dashboard/issues/11994
- https://github.com/rancher/dashboard/issues/11995

> This issue requires a QA template.

**Comment by richard-cox** [comment]
Some of the backend changes have already been implemented in 2.7.2
- SURE-5387
  - Some docs on the new UI are at https://github.com/rancher/steve#readme, https://github.com/rancher/rancher/tree/release/v2.7/tests/v2/integration/steveapi#readme

> Anything marked as `Development note` are implementation details for this issue and are candidates to spin out

Some are incoming in 2.7 Q2
- SURE-5698
  - Adds required searching
    - Development note - only single search term is supported. searching by multiple terms locally seems broken anyway https://github.com/rancher/dashboard/issues/8042
  - Filtering by one or more projects or namespaces
    - Development note - NOT is supported, aka filter by NOT list of system namespaces (i.e. user namespaces)
    - Development note - a maximum of 50 individual namespaces are expected. We need to handle this in UI

Some that we would like for 2.7 Q2 but are not blocking
- SURE-5735
  - Pagination of virtual resource (for instance Workloads)
  - Development note - If this is not delivered we would need to hide the Workloads list
- SURE-5733
  - Filtering/Sorting by aggregated fields (for instance Deployment Pod restarts)
- SURE-5734
  - Socket updates for paginated lists
  - Development note - See comments in 5734 for details on how we will mitigate it

**Comment by clayrisser** [comment]
I quit using Rancher because it's so slow. It's unusable. It's hogging 4 GB memory on a brand new cluster. It's been doing this ever since rancher 2.6 and there seems to be no improvements.

**Comment by richard-cox** [comment]
This _is_ a year old, and I can empathise with the frustration you've experienced. We are very actively working on a solution though (see linked issues and their prs for UI progress). Unfortunately API side hit a road block which has delayed things a bit. I'm happy to say though that we are targeting a tech preview of the feature in 2.9.0.

In addition 2.9.0 contains many UI performance improvements that assist both memory and CPU usage. It's worth giving that a try when released.

**Comment by clayrisser** [comment]
I will try again with 2.9.0, but if it requires running a large server, (more than 4 CPU) it's just not worth it.

I'm going to assume rancher works well for very large deployments that have resources to throw at it, but small deployments can't justify too much resources for it.

**Comment by chad-barensfeld-exa** [comment]
Please add pagination to the "new" UI. It's unusable when importing hundreds of clusters. We have to use the old UI which still has pagination. /g/clusters

**Comment by richard-cox** [comment]
@chad-barensfeld-exa Server-side pagination is a large project that we are currently targeting in and enabled by default in 2.11. In parallel we have been making a number of other performance improvements which have received a lot of positive feedback from the community and SUSE customers, including those using Ranchers with a large number of clusters.

Unfortunately the old UI is not supported and will soon be unavailable. It also did not use server-side pagination (instead normally only showed a very restricted set of resources). 

To help us with your specific performance issue would you be able to open a new github issue and provide as much detail as possible on what and where the performance is problematic, such as

- Does the blue spinner when reloading a page take very long time, or never stops? Does that happen always, or only some times?
- Does a page load slowly when the user first navigates to the UI?
- Does it take a long time to go from page to page?
- Does a list of resources take a long time to show any rows?
- Does the UI become unresponsive, clicks don't do anything?

Add concrete examples, eg.

- "Viewing a cluster's config from the Cluster Management page was just sitting on Loading"
- "Closing Rancher and opening a new Rancher instance in Chrome showed the blue spinning circle"
- "After reloading the page (CTRL+R) in about 3 minutes the UI would either eventually load or show a Fail Whale error (~50% of cases)"

If there's lots of places where performance isn't great, focus on one process they found most likely to see issues, or where the issues are worst.

Do all network requests take a long time to complete, or is there one or two in particular that take time?

**Comment by gaktive** [comment]
We have other tickets to track this work.
