### ISSUE TITLE
Epic: agent deployment configuration

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8536]
- [x] RKE2 (Vue): https://github.com/rancher/dashboard/issues/8533
- [x] RKE1 (Ember): https://github.com/rancher/dashboard/issues/8534
- [x] EKS (Ember): https://github.com/rancher/dashboard/issues/8535

**Comment by gaktive** [comment]
I'll use this ticket to watch what's going on. If things need to be shared between @aalves08 & @mantis-toboggan-md, we can ensure info is here and in the appropriate related tickets.

**Comment by gaktive** [comment]
All features in tickets now in To Test, so for tracking purposes, this looks done. However, in light of the security required label, need to check that everything's good on that front.

**Comment by gaktive** [comment]
Security was reviewed for the whole feature already.

**Comment by gaktive** [comment]
Features complete.

**Comment by slickwarren** [comment]
as of rancher v2.7-head (f0d4078) all agentCustomization tickets have been validated for rke2, k3s and rke1. Closing this issue
