### ISSUE TITLE
Epic: Improve extension maintainability and experience

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#8581]
Create the APIs used to configure and initialize extensions before the app fully bootstraps itself
- [x] https://github.com/rancher/dashboard/issues/8580
- [ ] https://github.com/rancher/dashboard/issues/8597
- [x] https://github.com/rancher/dashboard/issues/8582

Create reusable and composable layout components:
- [ ] https://github.com/rancher/dashboard/issues/8583
- [x] #8598
- [x] #8599
- [x] #8600
- [x] #8649

**Comment by codyrancher** [comment]
Closing since we will only likely do 3 of these. One is done and two are still open and labeled with area/plugins
