### ISSUE TITLE
Epic - Make finding resources easier

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#8676]
We need to rethink how users search for resources and objects across Rancher, Kubernetes and Custom definitons

Original Scope

- [ ] https://github.com/rancher/dashboard/issues/5091 (possible dupe here https://github.com/rancher/dashboard/issues/4151)
- [ ] https://github.com/rancher/dashboard/issues/5033
- [x] https://github.com/rancher/dashboard/issues/5798
- [x] https://github.com/rancher/dashboard/issues/7048

**Comment by manuelecarlini** [comment]
This first proposal includes a redesign of the modal for the resource search,
this will improve the readability and the look and feel, aligning the design to the upcoming new side menu for the navigation.

To change during the implementation developer side:
- The filter field should search also among the category title, not just the title of the page. This should solve the issue #5033
- For accessibility: Is it currently possible to select the pages with the keyboard arrows, but the list considers the category title as a selectable element (that is not), making the background color normally that appears on mouseover disappear,
this should be fixed allowing to navigate the list with the keyboard input only considering the pages. 

Version A has the link's color as you see in the UI
Version B reflects the design of the future side menu design
https://xd.adobe.com/view/ef149e76-09f9-418a-bce2-f948b67cd778-ba47/

All the resources will be displayed by default, but the user has the option to show only those pages containing at least one resource.

In the future, we'll think about removing the More Resource section from the side menu or/and add more functionalities
