### ISSUE TITLE
Epic: Improve RBAC experience

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#8812]
Epic for improving the user experience of creating and adding users and assigning roles and permissions in Rancher and downstream clusters

- [ ] https://github.com/rancher/dashboard/issues/6217
- [x] https://github.com/rancher/dashboard/issues/7522
- [x] https://github.com/rancher/dashboard/issues/8576
- [ ] https://github.com/rancher/dashboard/issues/6184
