### ISSUE TITLE
Epic: Improve Navigation

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#8813]
Navigation:
- [ ] https://github.com/rancher/dashboard/issues/4306
- [x] https://github.com/rancher/dashboard/issues/4431
- [x] https://github.com/rancher/dashboard/issues/5287
- [x] https://github.com/rancher/dashboard/issues/5816
- [ ] https://github.com/rancher/dashboard/issues/6067
- [ ] https://github.com/rancher/dashboard/issues/6103
- [x] https://github.com/rancher/dashboard/issues/6201
- [ ] https://github.com/rancher/dashboard/issues/8418
- [ ] https://github.com/rancher/dashboard/issues/8630
