### ISSUE TITLE
Extension UX Improvements

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#9013]
- [x] Add docs about annotations for version compatibility https://github.com/rancher/dashboard/pull/9135
- [ ] Update creators to add these annotations, so that a newly created extension will only work (by default) on the shell with the latest API https://github.com/rancher/dashboard/issues/9418
- [x] Add docs around `safemode` query parameter https://github.com/rancher/dashboard/pull/9135
- [ ] Add workflow to build extensions in a repo on push to master https://github.com/rancher/dashboard/issues/9419
- [ ] Workout how extension developers should persist data https://github.com/rancher/dashboard/issues/9420
   - We're going to attempt to do this one using settings
- [x] Verify standard users can use extensions and file an issue if it's not possible.
- [x] Better experience when developing against a rancher instance that already has your extension installed. https://github.com/rancher/dashboard/pull/9147

**Comment by aalves08** [comment]
@codyrancher can you elaborate on a couple of items you have described here? not sure what actions to take on those:
- Update creators to add these annotations, so that a newly created extension will only work (by default) on the shell with the latest API
- Add workflow to build extensions in a repo on push to master

**Comment by aalves08** [comment]
@jordojordo and @codyrancher can I get some feedback on the items i've commented? cheers 🙏

**Comment by aalves08** [comment]
Thanks for the feedback @jordojordo 🙏

**Comment by codyrancher** [comment]
> Update creators to add these annotations, so that a newly created extension will only work (by default) on the shell with the latest API

We have a mechanism (I believe via annotations) which allow the user to specify that an extension only works for a specific version of rancher. We should make it so that `yarn create @rancher/app my-app` will create an app which by default is only compatible with the latest version of rancher (maybe we can do something more granular than the latest).

I wanted this because when installing the ai chat extension to the opni instance of rancher it succeeded to install but then the pages failed to load because their instance is running Rancher 2.7.4 which was missing I believe the [addAction](https://rancher.github.io/dashboard/extensions/api/actions#addaction) api.

> Add workflow to build extensions in a repo on push to master

Not everyone wants to have a CI/CD like workflow. Some (again opni) would like to only build the extension when a release is created/tagged.

**Comment by aalves08** [comment]
Thanks for the feedback @codyrancher . Those are some good improvements 🙏

**Comment by aalves08** [comment]
Will close this issue, since the missing items are translated into individual issues:
https://github.com/rancher/dashboard/issues/9418
https://github.com/rancher/dashboard/issues/9419
https://github.com/rancher/dashboard/issues/9420
