### ISSUE TITLE
Malformed payloads cause excessive warning headers, potentially leading to 502 responses

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9016]
This is a follow up from https://github.com/rancher/dashboard/issues/9012 and there's more detail in the comments there.

Steve adds a few fields to all resources:
`metadata.fields`
`metadata.state`
`metadata.relationships` 
`status.conditions[i].error`
`status.conditions[i].transitioning`

When the user edits a resource, these are included in the payload, and each results in a warning header in the response. 

The ui has been sending these extra fields for a while and it's only recently become a problem due to the combo of k8s 1.25 validating by default, and steve including warning headers as of 2.7.2. There will need to be more discussion around how to handle this, potentially in coordination with backend work.

- [x] https://github.com/rancher/dashboard/issues/9371
- [ ] https://github.com/rancher/dashboard/issues/9372
- [ ] https://github.com/rancher/dashboard/issues/9294
- [ ] https://github.com/rancher/dashboard/issues/14340

**Comment by gaktive** [comment]
@KevinJoiner to flesh out some of the impact here and then file a related backend ticket to see what can be done in the API since though UI can truncate, new fields could be added.

@richard-cox to explore around this a bit.

**Comment by aalves08** [comment]
FYI @aalves08

**Comment by gaktive** [comment]
We need to dig into this some more since we could tackle the generic ones, but that may be 80% of what's there.

This feels like an epic that needs to be split up.

**Comment by richard-cox** [comment]
The two issues required to resolve this are...
- https://github.com/rancher/dashboard/issues/9371
- https://github.com/rancher/dashboard/issues/9372

**Comment by richard-cox** [comment]
Linking backend changes (which covers some of the common cases) - https://github.com/rancher/rancher/issues/41772

**Comment by richard-cox** [comment]
Linking issues
 
- Epic
  - https://github.com/rancher/dashboard/issues/9016 (in particular [this](https://github.com/rancher/dashboard/issues/9016#issuecomment-1572573830) comment) (this issue)
    - Step 1 - https://github.com/rancher/dashboard/issues/9371
    - Step 2 - https://github.com/rancher/dashboard/issues/9372
- Other Issues
  - https://github.com/rancher/dashboard/issues/9294
  - https://github.com/rancher/dashboard/issues/14340 (crossover with 9294)
