### ISSUE TITLE
Design blog kick off content - Epic

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#9085]
We want to publish content about our design work. Since there has been some related work around the active colour, the side menus and the buttons, we need to write different pieces and publish them in the correct order.

- Active state new colour
|- Apps bar -> Cluster Explorer navbar
|- New buttons

- Cards redesign

The Cards redesign work could be published at any time, but since we already have a spec document it would be interesting to work on the post and publish it soon.

Epic issues:
- [ ] https://github.com/rancher/dashboard/issues/9080
- [ ] https://github.com/rancher/dashboard/issues/9081
- [ ] https://github.com/rancher/dashboard/issues/9082
- [ ] https://github.com/rancher/dashboard/issues/9083
- [ ] https://github.com/rancher/dashboard/issues/9084
