### ISSUE TITLE
Card component redesign - Epic

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#9090]
We are trying to standardise how Cards are used in Rancher. The design work is in the [Cards redesign Confluence page](https://confluence.suse.com/display/CU/Cards+redesign). This is the Epic to track the whole work.

- [ ] https://github.com/rancher/dashboard/issues/8859
- [ ] https://github.com/rancher/dashboard/issues/9293
- [ ] https://github.com/rancher/dashboard/issues/9298

**Comment by gaktive** [comment]
I'll create another ticket to tackle the unnecessary cards for Q3 and push this ticket out to Q4 since additional styling updates could be done at the same time and more testing is required.
