### ISSUE TITLE
Cluster Explorer sidenav Epic

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#9188]
As a part of the general navigation improvement plan, we wanted to redesign the Cluster Explorer side navigation. This epic gathers all the issues from design to development.

- [x] https://github.com/rancher/dashboard/issues/8630
- [x] https://github.com/rancher/dashboard/issues/8835 
- [x] https://github.com/rancher/dashboard/issues/9189 

## Proposed Solution

- [x] Decouple the side nav into separate component: rancher/dashboard#9427
- [x] Highlight nav groups with selected children: rancher/dashboard#9428
- [x] Update icons & location in namespace: rancher/dashboard#9429
- [x] Enhance styles, width, etc: rancher/dashboard#9430

## Acceptance Criteria

- [ ] The sidenav is decoupled from the default layout, and it functions as a standalone component
- [ ] When a child item within a navigation group is selected, the corresponding group in the sidenav is visually highlighted as defined in the [design spec]
- [ ] The namespace icon is updated to the latest version and placed in the appropriate location within the sidenav, in alignment with the [design spec]
- [ ] Styles, including spacing, width, font size, etc., are updated to match the [design spec] for the sidenav
- [ ] Appropriate e2e or unit tests are written to prevent regressions and assert new functionality
- [ ] Changes are reviewed and approved by the design team to ensure they meet the [design spec]

### Design Spec

- https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/

[design spec]: https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/

### Discussion

Added by @aalves08 on **19/07/2023**:
> I think that this is a great opportunity to decouple the sidenav (make it as a component) from the default layout. We would benefit a lot from that work. There's similar work done here https://github.com/codyrancher/rancher-desktop/pull/1/files#diff-0c0232aeeb5da2a0b2ff8dadf8922e23b71d4c14da75d3d9aa1d99ca66937aec which can give great insights on how to achieve it with the current logic.

Added by @rak-phillip on **19/07/2023**:

> We also attempted to isolate the sidenav a while back but were not ready to take it. https://github.com/rancher/dashboard/pull/8000

**Comment by gaktive** [comment]
@rak-phillip @scures @kwwii and myself to sync on acceptance criteria (and find others).

**Comment by kwwii** [comment]
NOTE: This Epic does not include any colour changes.

**Comment by susesgartner** [comment]
I have been doing some testing for navigation sidebar in 2.8 and I noticed that there is a header for "Global Settings" and "Configuration" but there isn't a header for clusters. It may be a good idea to delineate downstream clusters in a similar way to the other 2 sections see the below image. 
<img width="300" alt="Screenshot 2023-10-11 at 12 30 18 PM" src="https://github.com/rancher/dashboard/assets/136753565/48a59c9b-34e7-427e-8b48-0deae7cd9f77">

**Comment by rak-phillip** [comment]
@susesgartner I think #9407 is the relevant issue for app bar discussions.

**Comment by susesgartner** [comment]
Ticket #9188 - Test Results - ✅ PASS
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Size, padding, spacing and namespace icon validation | PASS |
| 2. | Validate that side nav highlighting is working as intended | PASS |
| 3. | Validate that side nav works as intended while resizing browser window | PASS |
 
---

Verified with HA Helm on Rancher `v2.8-head`:
---
 
Scenario 1: Size, padding, spacing and namespace icon validation 
---
1. Validate the various size specifications listed in the design spec
2. Validate that the padding between elements is the appropriate size by inspecting the page and selecting the various UI elements.
3. Validate that the namespace icon is updated. 
4. Repeat 1-3 for both light and dark mode
 
Results: All of the above validations passed
 
--- 

Scenario 2: Validate that side nav highlighting is working as intended
---
1. Click an element in the sideNav
2. Verify if the font of the element becomes bold
3. Verify that the elements group gets highlighted
5. Repeat 1-3 for both light and dark mode
 
Results: the clicked element's text becomes bold and the elements group becomes highlighted

---
 
Scenario 3: Validate that side nav works as intended while resizing browser window
---
1. Resize the window as small as possible 
2. Validate that UI elements still are properly displayed.
3. Set the window to fullscreen and repeat step 2
4. Repeat 1-3 for both light and dark mode
 
Results: The resizing worked as intended and all UI elements maintained a normal appearance/were visible

**Comment by Josh-Diamond** [comment]
Reviewed all nested sub-tickets + have confirmed:
- The sidenav is decoupled from the default layout, and it functions as a standalone component
- When a child item within a navigation group is selected, the corresponding group in the sidenav is visually highlighted
  - not a blocker but enhancements to group highlighting has been requested [here](https://github.com/rancher/dashboard/issues/9799) and is targeted for `v2.8.x` milestone
  
 In addition to the above checks navigation, accessibility, styles and responsiveness have been tested + validated.
 
 Closing out this issue now 🎉
