### ISSUE TITLE
EPIC - Annotation display redesign

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9237]
The way annotations are displayed has several issues:

![image](https://github.com/rancher/dashboard/assets/120640736/c56cc35d-b5d0-4b1b-b8ff-4058c5eac8d6)

1. **Copy action**: a secondary button without margins; regular size, repeated all over the section; the label doesn’t say what will be copied.
2. **Card style**: two horizontal lines per item, too much visual noise.
3. **String colour**: insufficient contrast in light theme (works fine in dark theme)

Points 1. and 2. will be solved on https://github.com/rancher/dashboard/issues/9320
Point 3 will be solved on https://github.com/rancher/dashboard/issues/9319

- [x] https://github.com/rancher/dashboard/issues/9320
- [x] https://github.com/rancher/dashboard/issues/9319
- [ ] https://github.com/rancher/dashboard/issues/9321

The acceptance criteria for the DEV issue is to implement the changes of the two previous issues: rancher/dashboard#9320 and rancher/dashboard#9319
