### ISSUE TITLE
Accessibility Epic: Implement A11y

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#9392]
**Is your feature request related to a problem? Please describe.**

Accessibility features to make pages/components more accessible.

- [x] https://github.com/rancher/dashboard/issues/8986
- [x] https://github.com/rancher/dashboard/issues/9423
- [x] https://github.com/rancher/dashboard/issues/7968
- [ ] https://github.com/rancher/dashboard/issues/8191

**Comment by aalves08** [comment]
Let's close it. Even the issue that is open has been tackled yesterday. Thanks @codyrancher 🙏
