### ISSUE TITLE
E2E Tests for RKE2 provisioning

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9431]
This is the epic to capture areas that we should have e2e tests for.

This is blocked on getting the infrastructure to provision downstream clusters.

We need to consider the create and edit flows.

Below is a starting point

- [ ] credential selection / creation
- [ ] machine pool management
- [ ] custom node drivers
- [ ] extension hooks
- [ ] psa/psp functionality
- [ ] addon/chart management
- [ ] member management

**Comment by codyrancher** [comment]
Adding the appropriate labels and project for visibility
