### ISSUE TITLE
Improve UX for operations that take over a second to complete

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9500]
- We need to provider better feedback to the user when operations take
  - Longer than a second
  - Longer than ten seconds
- This could handled in generic components (CreateEdit) or where the specific action occurs
- This could involve requests from the BE to provider feedback, status updates, etc

Tasks

- [ ] Identify operations that take over a second, and over ten seconds to complete. 
- [ ] Determine UX for operations that take over a second, given locations
- [ ] Determine UX for operations that take over ten sections, given locations
- [ ] Implement UI updates to handle long running operations

**Comment by gaktive** [comment]
Upon discussion, closing this though this is what we want to move towards. Let's tackle the tangible or specific issues first.
