### ISSUE TITLE
Revamp / Remove Performance Settings

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9553]
- Review features served by settings on this page. The end goal is for the page to be removed
- Determine which ones should stay
  - features that stay should be enabled without an option to disable (entry in settings page)
  - at the moment this list is...
  - [ ] Inactivity
  - [ ] Websocket notifications
  - [ ] Resource Garbage Collection
  - [ ] Websocket Web Worker
- Determine which ones should be removed
  - features should be removed from code and page
  - at the moment this list is...
  - [ ] Incremental Loading (blocked on https://github.com/rancher/dashboard/issues/8527)
  - [ ] Manual Refresh (blocked on https://github.com/rancher/dashboard/issues/8527)
  - [ ] Namespace / Project Filtering (blocked on https://github.com/rancher/dashboard/issues/8527))

**Comment by gaktive** [comment]
This would be follow-up once we get other measures in since these would clean up temporary efforts for the initial boost in performance.

**Comment by richard-cox** [comment]
Note - the description needs updating following https://github.com/rancher/dashboard/issues/12873
